name: Build Pyinstaller application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
    #due to github actions building their own python distribution, downloading and installing the official release is required for legacy macOS support
      run: |
        wget https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg
        sudo installer -pkg python-3.9.13-macosx10.9.pkg -target /
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install requests pyinstaller tqdm bs4
    - name: Create PyInstaller Binary
      run: |
        pyinstaller fetcharchivetube.py --onefile
        python3 ./support/patchbinary.py
        codesign --force --deep -s - ./dist/fetcharchivetube
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: FetchArchiveTube-macOS
        path: ./dist/fetcharchivetube
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyinstaller tqdm bs4
    - name: Create PyInstaller Binary
      run: |
        pyinstaller fetcharchivetube.py --onefile --icon=.\images\Icon_Win.ico
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: FetchArchiveTube-Windows
        path: ./dist/fetcharchivetube.exe
  build-windows-xp:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.4.4
      uses: actions/setup-python@v4
      with:
        python-version: "3.4.4"
    - name: Install dependencies
      run: |
        pip install pefile==2019.4.18 urllib3==1.25.7 chardet==3.0.4 requests==2.22.0 pyinstaller==3.5 tqdm==4.54.0 beautifulsoup4==4.8.0 soupsieve==1.9.2 bpc-f2format
    - name: Create PyInstaller Binary
      run: |
        f2format .
        pyinstaller fetcharchivetube.py --onefile --icon=.\images\Icon_Win.ico
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: FetchArchiveTube-Windows
        path: ./dist/fetcharchivetube.exe
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyinstaller tqdm bs4
    - name: Create PyInstaller Binary
      run: |
        pyinstaller fetcharchivetube.py --onefile
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: FetchArchiveTube-Linux
        path: ./dist/fetcharchivetube

